### ISSUE TITLE
U4 - Hotelzimmer reservieren

### ISSUE THREAD

**Issue by alexisschaffer** [Lammer-FH/boutique-hotel-technikum-2024-ba#10]
## Story

> Als Gast möchte ich zu einem ausgewählten Zeitraum ein ausgewähltes Zimmer buchen um eine Unterkunft in meinem Urlaub zu haben .

## Details

Es besteht eine API Schnittstelle um eine Buchung zu einem Zimmer durchführen zu können. Diese ist in der API Dokumentation zu finden. Nachdem der Benutzer ein verfügbares Zimmer gefunden hat, soll er es Buchen können. 
Er muss dazu folgende Daten angeben:

- Vorname
- Nachname
- gültige E-Mail-Adresse
- E-Mail-Adresse bestätigen
- Frühstück Ja / Nein

Er soll vor dem endgültigen Absenden, nochmal die Möglichkeit haben, seine Buchungsdaten (inkl. Buchungszeitraum und Zimmerwahl) zu überprüfen und ggf. zu bearbeiten.

Nach erfolgter Buchung muss dem Benutzer eine Bestätigung angezeigt werden.

## Recommended Approach

- Machen Sie sich mit der Schnittstelle vertraut
- Analyse der zu übertragenden Daten
- Paperprototype inkl. Userflow und Errorhandling
- Bauen Sie zuerst den Store und die API Anbindung und dann das GUI

## Definition of Done
 
- [ ] Der Benutzer kann zu einem gewünschten Zeitraum ein gewünschtes Zimmer unter Angabe seiner vollstädnigen und korrekten Daten Buchen, wenn das Zimmer verfügbar ist
- [ ] Mögliche Fehlerfälle werden abgefangen und der Benutzer entsprechend darauf hingewiesen
- [ ] Der Benutzer kann seine daten vor Absenden nochmal überprüfen
- [ ] Der Benutzer erhält eine Bestätigung nach erfolgreicher Buchung
- [ ] Das Feature wurde in einem eigenen Branch eingecheckt und ins Git-Repository gepusht
- [ ] Das Feature wurde nach einem Code Review in den Master gemerged

## Task

- [x] #28
- [x] #29
