### ISSUE TITLE
U2 - Hotelzimmer Auswahl

### ISSUE THREAD

**Issue by alexisschaffer** [Lammer-FH/boutique-hotel-technikum-2024-ba#8]
## Story

> Als Gast möchte ich eine Übersicht über Hotelzimmer und die zugehörigen Details sehen können , um mir nach meinen Vorstellungen ein Zimmer auszusuchen.

## Details

Es besteht eine API Schnittstelle über die Informationen zu den Zimmern abgerufen werden können. Diese ist in der API Dokumentation zu finden. Im Ordner images/rooms des Repositories finden sich Bilder. Die Dateinamen entsprechen der jeweiligen Zimmer id. Es kann sein, dass die Bilder nicht alle gleich groß sind. Finden Sie auch dafür eine Lösung. 

Zu den Extras sollen Aussagekräftige Icons gestellt werden, damit der Benutzer sich gut zurechtfindet. Es sollen beim ersten Laden maximal 5 Hotelzimmer angezeigt werden. Das heißt, es bedarf einer Lösung, wie man eine ungerade Zahl an Zimmern gut darstellt und wie man auf Seite 2 (und später evtl. 3 und 4 - Ein Zubau von Zimmern ist für das kommende Jahr geplant) wechseln kann.

## Recommended Approach

- Machen Sie sich mit der Schnittstelle vertraut
- Analyse der Rückgabe Daten
- Paperprototype für die Anzeige und das Paging
- Welche Interaktionen sind notwendig?
- Machen Sie sich mit den bootstrap icons vertraut
- Wenn sie ein anderes Designsystem einsetzen, machen Sie sich mit den Icons dort vertraut
- Wählen Sie Icons für die Extras aus
- Verwenden Sie für die Pageination Buttons s.g. Buttongroups

## Definition of Done

- [ ] Hotelzimmer können mit Bild, Titel, Beschreibung und Extras angezeigt werden
- [ ] Auf Seite eins werden 5 Hotelzimmer angezeigt
- [ ] Es ist möglich weitere Seiten anzuzeigen: Pagination
- [ ] Die Extras werden mit Icons versehen, die das Extra repräsentieren
- [ ] Das Feature wurde in einem eigenen Branch eingecheckt und ins Git-Repository gepusht
- [ ] Das Feature wurde nach einem Code Review in den Master gemerged

## Tasks

- [x] #19
- [x] #18
