### ISSUE TITLE
U3 - Verfügbarkeit prüfen

### ISSUE THREAD

**Issue by alexisschaffer** [Lammer-FH/boutique-hotel-technikum-2024-ba#9]
## Story

>Als Gast möchte ich überprüfen ob ein bestimmtes Zimmer zum meinem gewünschten Reisezeitraum verfügbar ist , um festzustellen, ob ich das Zimmer werde buchen können .

## Details

Es besteht eine API Schnittstelle über die Informationen zu den Zimmern abgerufen werden können. Diese ist in der API Dokumentation zu finden. Der Benutzer soll in der Oberfläche die Möglichkeit haben, seinen Buchungszeitraum zu definieren. Sie haben hier freie Hand, wie sie das dem Benutzer am besten darstellen. Denken Sie innovativ und out of the box dabei.

## Recommended Approach

- Machen Sie sich mit der Schnittstelle vertraut
- Analyse der Rückgabe Daten
- Bilden Sie zwei bis drei Varianten, wie man dem Benutzer den Zeitraum definieren lassen könnte, wie man die Zimmerverfügbarkeit darstellt, etc.
- Denken Sie auch den Userflow, bzw. das Usecase Szenario durch, Welcher Fehlerfälle gibt es
- Überlegen Sie, wie sie neue Komponenten entwerfen müssen, oder alte erweitern / ändern, damit Ihre Idee des GUI auch aus Implementierungssicht gut umsetzbar ist
- Bauen Sie zuerst den Store und die API Anbindung und dann das GUI

## Definition of Done
 
- [ ] Der Benutzer kann über einen Datumsdialog den Zeitraum der Buchung festlegen
- [ ] der Benutzer bekommt klares Feedback über die Verfügbarkeit in diesem Zeitraum
- [ ] Mögliche Fehlerfälle werden abgefangen und der Benutzer entsprechend darauf hingewiesen
- [ ] Das Feature wurde in einem eigenen Branch eingecheckt und ins Git-Repository gepusht
- [ ] Das Feature wurde nach einem Code Review in den Master gemerged

## Tasks:

- [x] #24
- [x] #25
